## Numpy 

 It provides support for arrays and matrices,along with mathematical functions to operate on these data structures 



In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np 

## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
## 1d array

arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
## 2d array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
## Attributes of numpy

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type:",arr.dtype)
print("Item size(in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements):  6
Data type: int64
Item size(in bytes): 8


In [9]:
## Numpy Vectorized operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition: ",arr1+arr2)

### Element Wise Substraction
print("Substraction: ", arr1-arr2)

### Element Wise Multiplication
print("Multiplication: ", arr1*arr2)

### Element Wise Divison
print("Divison: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Divison:  [0.1 0.1 0.1 0.1 0.1]


In [10]:
### Universal Functions

arr=np.array([1,2,3,4,5,6,])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [11]:
## Array slicing and indexing 

arr=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [12]:
arr[0]

array([1, 2, 3, 4])

In [17]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [14]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
## Modify Array Elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [21]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [23]:
### Staistical concepts -- Normalization

## TO  hAVE A MEAN OF 0 AND STANDARD DEVIATION OF 1
data = np.array([1,2,3,4,5])

## Calculate the mean and standara deviation
mean=np.mean(data)
std_dev = np.std(data)

# Normalize the data 
normalized_data =(data - mean) / std_dev
print("Normalized data: ", normalized_data)

## Output:
#Normalized data : [-1.26491106 -0.63245553 0.63245553 1.26491106]

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
data =np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean= np.mean(data)
print("Mean:", mean)

#Median 
median = np.median(data)
print("Median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

#Variance 
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [30]:
## Logical operation 

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<=8)]

array([6, 7, 8])